### ISSUE TITLE
Building on windows with wasmer_wamr feature

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain-wasmer#117]
I have been unable to get these crates building on windows with the `wasmer_wamr` feature flag. 

I don't know the c or windows tooling well so am not sure the best approach. My understanding is the "official" windows tooling is cmake and MSVC as compiler.  There are also several projects porting gnu build tools to windows including MSYS2 and MinGW.

- wamr-micro-runtime windows support
  - It has documentation and CI for building the `iwasm.exe` executable on windows (https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/product-mini#windows), but not for building iwasm as a library
  - When attempting to build it as a library with MSVC it was throwing a ton of warnings and several errors. 
  - I opened a PR that resolved the errors and most of the warnings for our build flags (https://github.com/bytecodealliance/wasm-micro-runtime/pull/3762). It appears to build successfully now.
  - I have a branch of hc-wasmer (fork of wasmer on `wamr` branch) that uses wamr-micro-runtime with the noted changes: https://github.com/holochain/wasmer/tree/fix/win32-build
  
Current State:
- When attempting to build the fork of hc-wasmer linked above on a windows machine with cmake, msvc, and llvm installed:
  - wasm-micro-runtime builds
  - bingen generates bindings
  - crate fails to compile due to type inconsistencies between bindgen bindings and wasmer code interfacing with it
  - When modifying wasmer code to fix type inconsistencies
  - Get a huge error dump that link.exe failed

**Comment by ThetaSinner** [comment]
Have the wasmer team built this for Windows? Wondering if this will build as a dependency of a simple crate or whether it's just always hard/impossible to build for Windows?

Happy to try and help with this, but it'll have to be between other things at the moment unfortunately, with Holo stuff happening! What steps do I need to take, like branches and roughly the steps you've gone through, to get to a build failure for this on Windows?

**Comment by mattyg** [comment]
> Happy to try and help with this, but it'll have to be between other things at the moment unfortunately, with Holo stuff happening! What steps do I need to take, like branches and roughly the steps you've gone through, to get to a build failure for this on Windows?

Thanks! I did give the wasmer team a heads up about the issue and it sounds like they want to resolve it before including it in an actual release. 

- You can attempt build wasmer from this branch: https://github.com/holochain/wasmer/tree/fix/win32-build
- In [lib/api/build.rs](https://github.com/holochain/wasmer/blob/9e8979478931b51cf1f1e3534568b5b0909291ab/lib/api/build.rs#L2) you'll see that we are downloading the wasm-micro-runtime source code and then compiling it with the rust cmake wrapper crate.
- I'm guessing we will need different cmake settings in wasm-micro-runtime's [CMakeLists.txt](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/CMakeLists.txt) and/or we will need a different cmake call and system setup to do the compilation with MSYS2 or MinGW instead of MSVC.

**Comment by jost-s** [comment]
@mattyg We'd convert this to documenting that wamr is just supported under iOS by us. If there's another pull for this to work under windows, please comment here.

**Comment by mattyg** [comment]
Closing unless there is a pull for this. We will document that wamr is only supported on iOS in #128
