### ISSUE TITLE
Should require CI checks to pass

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain-wasmer#125]
This repository generally doesn't have the same branch protection settings that we have on other projects.

**Comment by ThetaSinner** [comment]
I'd like to get common branch protection rules applied across all our active projects in this org. You can see the branch protection rule template here -> https://github.com/holochain/hc-github-config/blob/main/main.go#L27

It's incomplete because it only targets the default branch and not release branches (like main-0.3, main-0.4 etc) but it shows the intention I'm aiming at.

The main thing for this change would be to define a single `"check"` step that checks all the required CI checks pass -> https://github.com/holochain/hc-github-config/blob/main/main.go#L49. Doing that has been given at least 3 different names across our repos and clearly I forgot to make Kitsune2 match when I added that so I'm not attached to `"check"`. We just need a consistent name -> https://github.com/holochain/kitsune2/blob/main/.github/workflows/test.yaml#L53.

**Comment by mattyg** [comment]
@ThetaSinner will pulumi update the branch protection rules for existing repos? Or only for new repos and we need to make the changes manually to get existing repos in line?
